### ISSUE TITLE
quic

### ISSUE THREAD

**Issue by ghost** [asticode/go-astiudp#1]
not sure if you know about quic, but its over udp but has all the benefits of tcp like congestion control etc.
its in golang. it will get tls 3.0 also very soon.

it is a replacement for webrtc in many way, so is a good candidate for video streaming etc, if thats what your into. 

https://en.wikipedia.org/wiki/QUIC
https://github.com/lucas-clemente/quic-go

might be a good option for you.

**Comment by asticode** [comment]
@gedw99 thanks! will definitely check it out!
